services:
  - type: web
    name: youtrend-fastapi
    env: python
    plan: free # Or your preferred plan
    region: oregon # Or your preferred region
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/api/status" # Assuming your status endpoint is at /api/status
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 # Specify your Python version, align with your development
      - key: REDIS_URL
        fromService:
          type: redis
          name: youtrend-redis
          property: connectionString
      - key: YOUTUBE_API_KEY
        sync: false # Keep this as sync: false; set sensitive value in Render dashboard
      - key: FASTAPI_SECRET_KEY
        generateValue: true # Render can generate a random secret key

  - type: redis
    name: youtrend-redis
    plan: free # Or your preferred plan
    region: oregon # Or your preferred region
    ipAllowList: [] # Configure if you need to restrict access, an empty list allows all Render services
    maxmemoryPolicy: allkeys-lru # Or another policy suitable for caching 